### PR TITLE
Fix wrong sql statement, file structure and add express router

### PR DESCRIPTION
**Pull request by RizkyArifNur**
I've made some changes to improve the repository such as :
1. Fix wrong file name on nodemon watch from **/index.js** to **/src/sever.js**
2. Fix wrong query on insert method
3. Implement express router (or also called as mini-app) so the audience can learn more how to dealing with routing schema in express, If you don't want, you can reject this PR and I will update it for you

### CODE REVIEW

**Comment by andriawan** [comment]
It seems good, 

for point 1 could you also change package.json in start scripts to point `src/server.js`

for point 2 i think it just a shortcut if object has the same name as table column. But it's okey to use your way for cleaner code

for point 3 it is good, make code cleaner :D

thanks anyway @RizkyArifNur

**Comment by andriawan** [comment]
I think it's all good. ready to be merged...thanks for the feedback @RizkyArifNur 😄

**Comment by RizkyArifNur** [comment]
Point 1. Already updated @andriawan, 
and for point 2 I already tested your code on my env, and it throws an error, coz you can't bind the insert statement like that, so I updated the SQL syntax an also the bound object too

**Comment by andriawan** [comment]
> Point 1. Already updated @andriawan,
> and for point 2 I already tested your code on my env, and it throws an error, coz you can't bind the insert statement like that, so I updated the SQL syntax an also the bound object too

image


But it's fine on my local, no error at all 😅 based on https://bezkoder.com/node-js-rest-api-express-mysql/

**Comment by RizkyArifNur** [comment]
@andriawan  Ohh interesting, here is what I found just a few moments ago when using your approach
image

**Comment by andriawan** [comment]
> @andriawan Ohh interesting, here is what I found just a few moments ago when using your approach
> image

I also does not implement backtick `member` and everything fine on my local

**Comment by RizkyArifNur** [comment]
I think the problem is the version of MYSQL that we're using,
I'm using 8.0.17

**Comment by andriawan** [comment]
i see, compatibility. I think we have to find out the best way for compatibility. Could you please solve this problem if you have a time😁 

i'm using mysql 5.7.29 and i have tested your latest code change, and still work. I think it's okey so far. No need additional config for compatibility😄

**Comment by RizkyArifNur** [comment]
Noted,
Maybe we can provide a docker-compose file for this issue,
but I don't know whether the audience will be confused or not, coz this repository is for basic knowledge, I don't want to bother the audience with another knowledge that not very necessary,
maybe, for now, we just need to write the supported MYSQL version in the Readme

**Comment by andriawan** [comment]
I think we can just use it later...wanna involve in website rantaudev development (Gatsby + tailwind) @RizkyArifNur ?😄 https://github.com/rantaudev/rantau.dev

**Comment by RizkyArifNur** [comment]
Sorry mas @andriawan, I'm not advanced at frontend development, If there's a backend system there, I can help you

**Pull request merged**
